language: java
jdk:
  - oraclejdk8
script: ant build
deploy:
  provider: releases
  user: $GITHUB_USERNAME
  password: $GITHUB_PASSWORD
  file_glob: true
  file: directory/*
  skip_cleanup: true
  on:
    tags: true
    
